# Generated by Django 5.0.7 on 2024-07-19 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
